"""Per-lesson dynamic enrichment (fun facts, interview questions, trivia quiz).

Generated by the local LLM the first time a user opens a lesson, cached in MongoDB
per (lesson_id, language). Falls back to content derived from the lesson itself
when Ollama is unavailable, so the UI always has something to render.
"""

from datetime import datetime, timezone
from typing import Any

from app.database import get_mongo
from app.models import Lesson
from app.services import ollama_service
from app.services.ollama_service import OllamaUnavailable

COLLECTION = "lesson_enrichment"


def _pick(value: Any, language: str) -> str:
    if isinstance(value, dict):
        return value.get(language) or value.get("en") or ""
    return str(value)


def _fallback(lesson: Lesson, language: str) -> dict[str, Any]:
    """Static enrichment derived from the lesson content when the LLM is down."""
    content = lesson.content or {}
    question = _pick(content.get("question", {}), language)
    definition = _pick(content.get("definition", {}), language)
    examples = [_pick(e, language) for e in content.get("examples", [])]

    first_paragraph = definition.split("\n\n")[0] if definition else ""
    quiz = []
    for ex in lesson.exercises:
        if ex.type == "multiple_choice" and len(quiz) < 2:
            options = [_pick(o, language) for o in ex.data.get("options", [])]
            correct = ex.solution.get("correct", [0])
            if options and correct:
                quiz.append(
                    {
                        "question": _pick(ex.data.get("prompt", {}), language),
                        "options": options,
                        "correct_index": int(correct[0]),
                    }
                )
    return {
        "fun_facts": examples[:3],
        "interview_questions": (
            [{"question": question, "suggested_answer": first_paragraph}] if question else []
        ),
        "quiz": quiz,
        "source": "fallback",
    }


def get_enrichment(lesson: Lesson, language: str, user_id: int | None, refresh: bool = False) -> dict[str, Any]:
    mongo = None
    try:
        mongo = get_mongo()
    except Exception:
        pass

    if mongo is not None and not refresh:
        try:
            cached = mongo[COLLECTION].find_one(
                {"lesson_id": lesson.id, "language": language, "source": "llm"}
            )
            if cached:
                return {
                    "fun_facts": cached["fun_facts"],
                    "interview_questions": cached["interview_questions"],
                    "quiz": cached["quiz"],
                    "source": "llm",
                }
        except Exception:
            pass

    topic = _pick(lesson.content.get("question", {}), language)
    definition = _pick(lesson.content.get("definition", {}), language)
    try:
        generated = ollama_service.generate_lesson_enrichment(
            topic=topic, definition=definition, language=language, user_id=user_id
        )
    except OllamaUnavailable:
        return _fallback(lesson, language)

    if mongo is not None:
        try:
            mongo[COLLECTION].replace_one(
                {"lesson_id": lesson.id, "language": language},
                {
                    "lesson_id": lesson.id,
                    "language": language,
                    "source": "llm",
                    **generated,
                    "created_at": datetime.now(timezone.utc),
                },
                upsert=True,
            )
        except Exception:
            pass

    return {**generated, "source": "llm"}
