from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.database import get_db, get_mongo
from app.models import Exercise, ExerciseAttempt, User
from app.schemas import AttemptRequest, AttemptResponse, SolutionRevealResponse
from app.services import badge_service, ollama_service, validation_service
from app.services.ollama_service import OllamaUnavailable
from app.security import get_current_user

router = APIRouter(prefix="/api/exercises", tags=["exercises"])

REVEAL_COLLECTION = "exercise_model_answers"


def _pick_lang(value, language: str) -> str:
    if isinstance(value, dict):
        return value.get(language) or value.get("en") or ""
    return str(value)


@router.post("/{exercise_id}/attempt", response_model=AttemptResponse)
def submit_attempt(
    exercise_id: int,
    payload: AttemptRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    exercise = db.get(Exercise, exercise_id)
    if exercise is None:
        raise HTTPException(status_code=404, detail="exercise_not_found")

    feedback: str | None = None
    if exercise.validation_mode == "llm":
        answer_text = str(payload.answer.get("text", "")).strip()
        if not answer_text:
            raise HTTPException(status_code=422, detail="empty_answer")
        prompt = _pick_lang(exercise.data.get("prompt", {}), user.language)
        criteria = _pick_lang(exercise.solution.get("criteria", {}), user.language)
        reference = exercise.solution.get("reference")
        try:
            correct, feedback = ollama_service.validate_answer(
                prompt=prompt,
                answer=answer_text,
                criteria=criteria,
                reference=reference,
                language=user.language,
                user_id=user.id,
            )
        except OllamaUnavailable:
            raise HTTPException(status_code=503, detail="llm_unavailable")
    else:
        correct = validation_service.validate_static(exercise.type, payload.answer, exercise.solution)

    db.add(
        ExerciseAttempt(
            user_id=user.id,
            exercise_id=exercise.id,
            answer=payload.answer,
            is_correct=correct,
            feedback=feedback,
        )
    )
    db.commit()

    new_badges = badge_service.check_attempt_badges(db, user)

    # Reveal the solution only after an attempt (right or wrong) so the UI can explain.
    solution_out = None
    if exercise.validation_mode == "static":
        solution_out = {k: v for k, v in exercise.solution.items()}
        if "explanation" in exercise.data:
            solution_out["explanation"] = exercise.data["explanation"]
    return AttemptResponse(correct=correct, feedback=feedback, solution=solution_out, new_badges=new_badges)


@router.get("/{exercise_id}/solution", response_model=SolutionRevealResponse)
def reveal_solution(
    exercise_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return a model correct answer for an LLM-validated exercise.

    Generated by the local LLM (cached in MongoDB per exercise+language); falls
    back to the seed's reference answer when Ollama is unavailable.
    """
    exercise = db.get(Exercise, exercise_id)
    if exercise is None:
        raise HTTPException(status_code=404, detail="exercise_not_found")
    if exercise.validation_mode != "llm":
        raise HTTPException(status_code=400, detail="not_llm_exercise")

    language = user.language
    mongo = None
    try:
        mongo = get_mongo()
    except Exception:
        pass

    if mongo is not None:
        try:
            cached = mongo[REVEAL_COLLECTION].find_one(
                {"exercise_id": exercise.id, "language": language}
            )
            if cached:
                return SolutionRevealResponse(answer=cached["answer"], source=cached["source"])
        except Exception:
            pass

    prompt = _pick_lang(exercise.data.get("prompt", {}), language)
    criteria = _pick_lang(exercise.solution.get("criteria", {}), language)
    reference = exercise.solution.get("reference")
    try:
        answer = ollama_service.generate_model_answer(
            prompt=prompt,
            criteria=criteria,
            reference=reference,
            exercise_type=exercise.type,
            code_language=exercise.data.get("language"),
            language=language,
            user_id=user.id,
        )
        source = "llm"
    except OllamaUnavailable:
        if not reference:
            raise HTTPException(status_code=503, detail="llm_unavailable")
        answer, source = str(reference), "reference"

    if mongo is not None and source == "llm":
        try:
            mongo[REVEAL_COLLECTION].replace_one(
                {"exercise_id": exercise.id, "language": language},
                {
                    "exercise_id": exercise.id,
                    "language": language,
                    "answer": answer,
                    "source": source,
                    "created_at": datetime.now(timezone.utc),
                },
                upsert=True,
            )
        except Exception:
            pass

    return SolutionRevealResponse(answer=answer, source=source)
